server:
  port: 9000
spring:
  application:
    name: msc-depart-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
        # 配置管控台的主机地址+端口
        dashboard: localhost:8888
        # 传输配置数据端口
        port: 8719
      datasource:
        my-ds-flow:
          nacos:
            server-add: localhost:8848
            data-id: consumer_rule
            rule-type: flow
            data-type: json
