server:
  # 默认端口是8080
  port: 8080
spring:
  application:
    name: msc-consumer-depart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
        # 配置管控台的主机地址+端口
        dashboard: localhost:8888
        # 传输配置数据端口
        port: 8719
      datasource: # 配置数据源头：流控规则
        my-ds-flow:
          nacos:
            #配置中心地址
            server-add: localhost:8848
            # 配置中心配置文件的名称
            data-id: my_consumer_rule # 配置文件名称
            # 规则类型
            rule-type: flow # 规则类型
            # 配置文件类型
            data-type: json # 配置文件类型
feign:
  # 配置开启feign对sentinel的支持
  sentinel:
    enabled: true
