server:
  # 默认端口是8080
  port: 8080
spring:
  application:
    name: msc-consumer-depart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
        # 配置管控台的主机地址+端口
        dashboard: localhost:8888
        # 传输配置数据端口
        port: 8719
