server:
  # 默认端口是8080
  port: 9001
spring:
  application:
    name: msc-gateway-api
  cloud:
    gateway:
      discovery:
        # 配置开启定位器
        locator:
          enabled: true
      routes:
        # 路由到depart服务
        - id: depart_route
          uri: lb://msc-consumer-depart
          predicates:
            - Path=/consumer/depart/get/**
        # 路由到staff服务
        - id: staff_route
          uri: lb://msc-consumer-staff
          predicates:
            - Path=/consumer/staff/get/**
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
        # 配置管控台的主机地址+端口
        dashboard: localhost:8888
        # 传输配置数据端口
        port: 8719
